name: 'Test action'
description: 'description'

inputs:
  # meta
  pull:
    description: 'whether to pull'
    required: true
    default: true
  deploy:
    description: 'name of the service that needs to be deployed'
  script:
    description: 'additional script if needed'
  # ssh
  host:
    description: 'host'
    required: true
  port:
    description: 'port'
    required: true
    default: 22
  username:
    description: 'username'
  password:
    description: 'password'

runs:
  using: 'composite'
  steps:
    - name: Deploy to ssh server
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        script : |
          . $HOME/.profile
          cd "$DEPLOYMENT_DIR"
          CURRENT_BRANCH=$(git branch --show-current)
          [ ${{ inputs.pull }} = 'true' -a ${{ github.ref_name }} = "$CURRENT_BRANCH" ] && \
            git fetch origin "$CURRENT_BRANCH"
            git reset --hard "origin/$CURRENT_BRANCH"
          [ -n '${{ inputs.deploy }}' ] && make deploy ${{ inputs.deploy }}
          if [ -n '${{ inputs.script }}' ]; then
            ${{ inputs.script }}
          fi
