name: 'Test action'
description: 'description'
inputs:
  pull:
    description: 'whether to pull'
    required: true
    default: true
  host:
    description: 'host'
    required: true
  port:
    description: 'port'
    required: true
    default: 22
  username:
    description: 'username'
  password:
    description: 'password'
runs:
  using: 'composite'
  steps:
    - name: Deploy to ssh server
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        script : |
          . $HOME/.profile
          cd "$DEPLOYMENT_DIR"
          CURRENT_BRANCH=$(git branch --show-current)
          echo ${{ inputs.pull }}
          [ ${{ github.ref_name }} = "$CURRENT_BRANCH" ] && git pull origin "$CURRENT_BRANCH"

